company_dictionary = {
    'MSFT': 'Microsoft Corp',
    'AAPL': 'Apple Inc',
    'NVDA': 'NVIDIA Corp',
    'AMZN': 'Amazon.com Inc',
    'TSLA': 'Tesla Inc',
    'META': 'Meta Platforms Inc',
    'GOOGL': 'Alphabet Inc',
    'GOOG': 'Alphabet Inc',
    'AVGO': 'Broadcom Inc',
    'PEP': 'PepsiCo Inc',
    'COST': 'Costco Wholesale Corp',
    'ADBE': 'Adobe Inc',
    'CSCO': 'Cisco Systems Inc',
    'NFLX': 'Netflix Inc',
    'AMD': 'Advanced Micro Devices Inc',
    'CMCSA': 'Comcast Corp',
    'TMUS': 'T-Mobile US Inc',
    'TXN': 'Texas Instruments Inc',
    'HON': 'Honeywell International Inc',
    'INTC': 'Intel Corp',
    'QCOM': 'QUALCOMM Inc',
    'INTU': 'Intuit Inc',
    'AMGN': 'Amgen Inc',
    'AMAT': 'Applied Materials Inc',
    'ISRG': 'Intuitive Surgical Inc',
    'SBUX': 'Starbucks Corp',
    'MDLZ': 'Mondelez International Inc',
    'BKNG': 'Booking Holdings Inc',
    'GILD': 'Gilead Sciences Inc',
    'ADI': 'Analog Devices Inc',
    'ADP': 'Automatic Data Processing Inc',
    'VRTX': 'Vertex Pharmaceuticals Inc',
    'LRCX': 'Lam Research Corp',
    'PANW': 'Palo Alto Networks Inc',
    'REGN': 'Regeneron Pharmaceuticals Inc',
    'PYPL': 'PayPal Holdings Inc',
    'CSX': 'CSX Corp',
    'MU': 'Micron Technology Inc',
    'SNPS': 'Synopsys Inc',
    'ATVI': 'Activision Blizzard Inc',
    'KLAC': 'KLA Corp',
    'CDNS': 'Cadence Design Systems Inc',
    'ASML': 'ASML Holding NV',
    'MELI': 'MercadoLibre Inc',
    'MNST': 'Monster Beverage Corp',
    'FTNT': 'Fortinet Inc',
    'ORLY': "O'Reilly Automotive Inc",
    'MAR': 'Marriott International Inc/MD',
    'CHTR': 'Charter Communications Inc',
    'ABNB': 'Airbnb Inc',
    'NXPI': 'NXP Semiconductors NV',
    'MRVL': 'Marvell Technology Inc',
    'DXCM': 'Dexcom Inc',
    'CTAS': 'Cintas Corp',
    'MCHP': 'Microchip Technology Inc',
    'MRNA': 'Moderna Inc',
    'LULU': 'Lululemon Athletica Inc',
    'WDAY': 'Workday Inc',
    'KDP': 'Keurig Dr Pepper Inc',
    'AEP': 'American Electric Power Co Inc',
    'KHC': 'Kraft Heinz Co/The',
    'PDD': 'PDD Holdings Inc ADR',
    'ADSK': 'Autodesk Inc',
    'CPRT': 'Copart Inc',
    'PCAR': 'PACCAR Inc',
    'BIIB': 'Biogen Inc',
    'EXC': 'Exelon Corp',
    'IDXX': 'IDEXX Laboratories Inc',
    'PAYX': 'Paychex Inc',
    'ODFL': 'Old Dominion Freight Line Inc',
    'ON': 'ON Semiconductor Corp',
    'AZN': 'AstraZeneca PLC ADR',
    'ROST': 'Ross Stores Inc',
    'GEHC': 'GE HealthCare Technologies Inc',
    'SGEN': 'Seagen Inc',
    'CSGP': 'CoStar Group Inc',
    'EA': 'Electronic Arts Inc',
    'XEL': 'Xcel Energy Inc',
    'GFS': 'GLOBALFOUNDRIES Inc',
    'FAST': 'Fastenal Co',
    'CTSH': 'Cognizant Technology Solutions Corp',
    'VRSK': 'Verisk Analytics Inc',
    'CRWD': 'Crowdstrike Holdings Inc',
    'DLTR': 'Dollar Tree Inc',
    'BKR': 'Baker Hughes Co',
    'WBD': 'Warner Bros Discovery Inc',
    'CEG': 'Constellation Energy Corp',
    'ILMN': 'Illumina Inc',
    'DDOG': 'Datadog Inc',
    'ANSS': 'ANSYS Inc',
    'TEAM': 'Atlassian Corp',
    'ALGN': 'Align Technology Inc',
    'WBA': 'Walgreens Boots Alliance Inc',
    'EBAY': 'eBay Inc',
    'FANG': 'Diamondback Energy Inc',
    'ENPH': 'Enphase Energy Inc',
    'ZS': 'Zscaler Inc',
    'SIRI': 'Sirius XM Holdings Inc',
    'ZM': 'Zoom Video Communications Inc',
    'JD': 'JD.com Inc ADR',
    'LCID': 'Lucid Group Inc'
}
# from the nasdaq